import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Roboto_Slab } from "next/font/google";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import AppProvider from "@/context/AppContext";
import Modal from "@/components/Modal";
import { Suspense } from "react";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "300"],
  variable: "--font-roboto",
});

const roboto_slab = Roboto_Slab({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-roboto-slab",
});

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "Markdown Editor",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="overflow-hidden" lang="en">
      <body
        className={`${roboto.variable} ${roboto_slab.variable} ${roboto_mono.variable} dark overflow-hidden md:overflow-auto`}
      >
        <Suspense>
          <AppProvider>
            {children}
            <Modal />
          </AppProvider>
        </Suspense>
      </body>
    </html>
  );
}
